// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using GONet;
using GONet.Utils;
using GONet.Generation;

namespace Assets.Code.GONet.Editor.Generation
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System.Text.RegularExpressions;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate : GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\n");
            this.Write("\r\n");
            this.Write("\r\nusing System;\r\nusing System.IO;\r\nusing System.Linq;\r\nusing System.Text;\r\nusing " +
                    "UnityEngine;\r\nusing GONet;\r\n\r\nnamespace GONet.Generation\r\n{\r\n\tinternal sealed cl" +
                    "ass ");
            
            #line 24 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" : GONetParticipant_AutoMagicalSyncCompanion_Generated\r\n    {\r\n");
            
            #line 26 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"

	int overallCount = 0;
	Array.ForEach(uniqueEntry.ComponentMemberNames_By_ComponentTypeFullName, uE => overallCount += uE.autoSyncMembers.Length);

	int singleCount = uniqueEntry.ComponentMemberNames_By_ComponentTypeFullName.Length;
	for (int iSingle = 0; iSingle < singleCount; ++iSingle)
	{
		GONetParticipant_ComponentsWithAutoSyncMembers_Single single = uniqueEntry.ComponentMemberNames_By_ComponentTypeFullName[iSingle];

            
            #line default
            #line hidden
            this.Write("\t\tprivate ");
            
            #line 35 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(single.componentTypeFullName));
            
            #line default
            #line hidden
            this.Write(" _");
            
            #line 35 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(single.componentTypeName));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\tinternal ");
            
            #line 36 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(single.componentTypeFullName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 36 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(single.componentTypeName));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t{\r\n\t\t\tget\r\n\t\t\t{\r\n\t\t\t\tif ((object)_");
            
            #line 40 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(single.componentTypeName));
            
            #line default
            #line hidden
            this.Write(" == null)\r\n\t\t\t\t{\r\n\t\t\t\t\t_");
            
            #line 42 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(single.componentTypeName));
            
            #line default
            #line hidden
            this.Write(" = gonetParticipant.GetComponent<");
            
            #line 42 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(single.componentTypeFullName));
            
            #line default
            #line hidden
            this.Write(">();\r\n\t\t\t\t}\r\n\t\t\t\treturn _");
            
            #line 44 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(single.componentTypeName));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t}\r\n\t\t}\r\n\r\n");
            
            #line 48 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
	}
            
            #line default
            #line hidden
            this.Write("\r\n        internal ");
            
            #line 50 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("(GONetParticipant gonetParticipant) : base(gonetParticipant)\r\n\t\t{\r\n\t\t\tvaluesCount" +
                    " = ");
            
            #line 52 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(overallCount));
            
            #line default
            #line hidden
            this.Write(@";
		    
			lastKnownValueChangesSinceLastCheck = lastKnownValuesChangedArrayPool.Borrow((int)valuesCount);
			Array.Clear(lastKnownValueChangesSinceLastCheck, 0, lastKnownValueChangesSinceLastCheck.Length);

			valuesChangesSupport = valuesChangesSupportArrayPool.Borrow((int)valuesCount);
			
");
            
            #line 59 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"

	int iOverall = 0;
	singleCount = uniqueEntry.ComponentMemberNames_By_ComponentTypeFullName.Length;
	for (int iSingle = 0; iSingle < singleCount; ++iSingle)
	{
		GONetParticipant_ComponentsWithAutoSyncMembers_Single single = uniqueEntry.ComponentMemberNames_By_ComponentTypeFullName[iSingle];
		int singleMemberCount = single.autoSyncMembers.Length;
		for (int iSingleMember = 0; iSingleMember < singleMemberCount; ++iSingleMember)
        {
			GONetParticipant_ComponentsWithAutoSyncMembers_SingleMember singleMember = single.autoSyncMembers[iSingleMember];

            
            #line default
            #line hidden
            this.Write("\t\t\tvar support");
            
            #line 70 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(iOverall));
            
            #line default
            #line hidden
            this.Write(" = valuesChangesSupport[");
            
            #line 70 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(iOverall));
            
            #line default
            #line hidden
            this.Write("] = valueChangeSupportArrayPool.Borrow();\r\n\t\t\tsupport");
            
            #line 71 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(iOverall));
            
            #line default
            #line hidden
            this.Write(".syncCompanion = this;\r\n\t\t\tsupport");
            
            #line 72 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(iOverall));
            
            #line default
            #line hidden
            this.Write(".index = ");
            
            #line 72 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(iOverall));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\tsupport");
            
            #line 73 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(iOverall));
            
            #line default
            #line hidden
            this.Write(".syncAttribute_ProcessingPriority = ");
            
            #line 73 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(singleMember.attribute.ProcessingPriority));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\tsupport");
            
            #line 74 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(iOverall));
            
            #line default
            #line hidden
            this.Write(".syncAttribute_ProcessingPriority_GONetInternalOverride = ");
            
            #line 74 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(singleMember.attribute.ProcessingPriority_GONetInternalOverride));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n");
            
            #line 76 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"

			iOverall++;
		}
	}

            
            #line default
            #line hidden
            this.Write("\t\t}\r\n\r\n        internal override void SetAutoMagicalSyncValue(byte index, object " +
                    "value)\r\n\t\t{\r\n\t\t\tswitch (index)\r\n\t\t\t{\r\n");
            
            #line 87 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"

	iOverall = 0;
	singleCount = uniqueEntry.ComponentMemberNames_By_ComponentTypeFullName.Length;
	for (int iSingle = 0; iSingle < singleCount; ++iSingle)
	{
		GONetParticipant_ComponentsWithAutoSyncMembers_Single single = uniqueEntry.ComponentMemberNames_By_ComponentTypeFullName[iSingle];
		int singleMemberCount = single.autoSyncMembers.Length;
		for (int iSingleMember = 0; iSingleMember < singleMemberCount; ++iSingleMember)
        {
			GONetParticipant_ComponentsWithAutoSyncMembers_SingleMember singleMember = single.autoSyncMembers[iSingleMember];

            
            #line default
            #line hidden
            this.Write("\t\t\t\tcase ");
            
            #line 98 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(iOverall++));
            
            #line default
            #line hidden
            this.Write(":\r\n\t\t\t\t\t");
            
            #line 99 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(single.componentTypeName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 99 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(singleMember.memberName));
            
            #line default
            #line hidden
            this.Write(" = (");
            
            #line 99 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(singleMember.memberTypeFullName));
            
            #line default
            #line hidden
            this.Write(")value;\r\n\t\t\t\t\treturn;\r\n");
            
            #line 101 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
		}
	}

            
            #line default
            #line hidden
            this.Write("\t\t\t}\r\n\t\t}\r\n\r\n        internal override object GetAutoMagicalSyncValue(byte index)" +
                    "\r\n\t\t{\r\n\t\t\tswitch (index)\r\n\t\t\t{\r\n");
            
            #line 111 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"

	iOverall = 0;
	singleCount = uniqueEntry.ComponentMemberNames_By_ComponentTypeFullName.Length;
	for (int iSingle = 0; iSingle < singleCount; ++iSingle)
	{
		GONetParticipant_ComponentsWithAutoSyncMembers_Single single = uniqueEntry.ComponentMemberNames_By_ComponentTypeFullName[iSingle];
		int singleMemberCount = single.autoSyncMembers.Length;
		for (int iSingleMember = 0; iSingleMember < singleMemberCount; ++iSingleMember)
        {
			GONetParticipant_ComponentsWithAutoSyncMembers_SingleMember singleMember = single.autoSyncMembers[iSingleMember];

            
            #line default
            #line hidden
            this.Write("\t\t\t\tcase ");
            
            #line 122 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(iOverall++));
            
            #line default
            #line hidden
            this.Write(":\r\n\t\t\t\t\treturn ");
            
            #line 123 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(single.componentTypeName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 123 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(singleMember.memberName));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 124 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
		}
	}

            
            #line default
            #line hidden
            this.Write("\t\t\t}\r\n\r\n\t\t\treturn null;\r\n\t\t}\r\n\r\n        internal override void SerializeAll(Utils" +
                    ".BitStream bitStream_appendTo)\r\n        {\r\n");
            
            #line 134 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"

	iOverall = 0;
	singleCount = uniqueEntry.ComponentMemberNames_By_ComponentTypeFullName.Length;
	for (int iSingle = 0; iSingle < singleCount; ++iSingle)
	{
		GONetParticipant_ComponentsWithAutoSyncMembers_Single single = uniqueEntry.ComponentMemberNames_By_ComponentTypeFullName[iSingle];
		int singleMemberCount = single.autoSyncMembers.Length;
		for (int iSingleMember = 0; iSingleMember < singleMemberCount; ++iSingleMember)
        {
			GONetParticipant_ComponentsWithAutoSyncMembers_SingleMember singleMember = single.autoSyncMembers[iSingleMember];

            
            #line default
            #line hidden
            this.Write("\t\t\t{ // ");
            
            #line 145 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(single.componentTypeName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 145 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(singleMember.memberName));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 146 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"

			string singleMember_memberTypeFullName = singleMember.memberTypeFullName;
			// switch () boo hoo no switch for string because teh case values are not constant!!!  TODO Must make the following more performant!
            {
				if (singleMember_memberTypeFullName == typeof(bool).FullName)
                {

            
            #line default
            #line hidden
            this.Write("\t\t\t\tbitStream_appendTo.WriteBit(_");
            
            #line 153 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(single.componentTypeName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 153 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(singleMember.memberName));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 154 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"

				}
				else if (singleMember_memberTypeFullName == typeof(float).FullName)
				{

            
            #line default
            #line hidden
            this.Write("\t\t\t\tbitStream_appendTo.WriteFloat(_");
            
            #line 159 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(single.componentTypeName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 159 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(singleMember.memberName));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 160 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"

				}
				else if (singleMember_memberTypeFullName == typeof(long).FullName)
				{

            
            #line default
            #line hidden
            this.Write("\t\t\t\tbitStream_appendTo.WriteLong(_");
            
            #line 165 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(single.componentTypeName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 165 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(singleMember.memberName));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 166 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"

				}
				else if (singleMember_memberTypeFullName == typeof(uint).FullName)
				{

            
            #line default
            #line hidden
            this.Write("\t\t\t\tbitStream_appendTo.WriteUInt(_");
            
            #line 171 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(single.componentTypeName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 171 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(singleMember.memberName));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 172 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"

				}
				else if (singleMember_memberTypeFullName == typeof(string).FullName)
                {

            
            #line default
            #line hidden
            this.Write("                bitStream_appendTo.WriteString(_");
            
            #line 177 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(single.componentTypeName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 177 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(singleMember.memberName));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 178 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"

				}
				else if (singleMember_memberTypeFullName == typeof(byte).FullName)
				{

            
            #line default
            #line hidden
            this.Write("\t\t\t\tbitStream_appendTo.WriteByte(_");
            
            #line 183 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(single.componentTypeName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 183 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(singleMember.memberName));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 184 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"

				}
				else if (singleMember_memberTypeFullName == typeof(ushort).FullName)
				{

            
            #line default
            #line hidden
            this.Write("\t\t\t\tbitStream_appendTo.WriteUShort(_");
            
            #line 189 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(single.componentTypeName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 189 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(singleMember.memberName));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 190 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"

				}
                else if (singleMember_memberTypeFullName == typeof(short).FullName
				 || singleMember_memberTypeFullName == typeof(int).FullName
				 || singleMember_memberTypeFullName == typeof(sbyte).FullName
				 || singleMember_memberTypeFullName == typeof(double).FullName)
				{

            
            #line default
            #line hidden
            this.Write("\t\t\t\tbyte[] bytes = BitConverter.GetBytes(_");
            
            #line 198 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(single.componentTypeName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 198 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(singleMember.memberName));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t\t\tint count = bytes.Length;\r\n\t\t\t\tfor (int i = 0; i < count; ++i)\r\n\t\t\t\t{\r\n\t\t" +
                    "\t\t\tbitStream_appendTo.WriteByte(bytes[i]);\r\n\t\t\t\t}\r\n");
            
            #line 204 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"

				}
			}
            
            #line default
            #line hidden
            this.Write("\t\t\t}\r\n");
            
            #line 208 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
		}
	}

            
            #line default
            #line hidden
            this.Write(@"        }

        internal override void SerializeSingle(Utils.BitStream bitStream_appendTo, byte singleIndex)
        {
            throw new NotImplementedException();
        }

        /// <summary>
        ///  Deserializes all values from <paramref name=""bitStream_readFrom""/> and uses them to modify appropriate member variables internally.
        /// </summary>
        internal override void DeserializeInitAll(Utils.BitStream bitStream_readFrom)
        {
");
            
            #line 223 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"

	iOverall = 0;
	singleCount = uniqueEntry.ComponentMemberNames_By_ComponentTypeFullName.Length;
	for (int iSingle = 0; iSingle < singleCount; ++iSingle)
	{
		GONetParticipant_ComponentsWithAutoSyncMembers_Single single = uniqueEntry.ComponentMemberNames_By_ComponentTypeFullName[iSingle];
		int singleMemberCount = single.autoSyncMembers.Length;
		for (int iSingleMember = 0; iSingleMember < singleMemberCount; ++iSingleMember)
        {
			GONetParticipant_ComponentsWithAutoSyncMembers_SingleMember singleMember = single.autoSyncMembers[iSingleMember];

            
            #line default
            #line hidden
            this.Write("\t\t\t{ // ");
            
            #line 234 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(single.componentTypeName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 234 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(singleMember.memberName));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 235 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"

			string singleMember_memberTypeFullName = singleMember.memberTypeFullName;
			// switch () boo hoo no switch for string because teh case values are not constant!!!  TODO Must make the following more performant!
            {
				if (singleMember_memberTypeFullName == typeof(bool).FullName)
                {

            
            #line default
            #line hidden
            
            #line 242 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
					if (singleMember.isField) {
            
            #line default
            #line hidden
            this.Write("                bitStream_readFrom.ReadBit(out _");
            
            #line 243 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(single.componentTypeName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 243 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(singleMember.memberName));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 244 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
					} else {
            
            #line default
            #line hidden
            this.Write("\t\t\t\tbool value;\r\n                bitStream_readFrom.ReadBit(out value);\r\n\t\t\t\t_");
            
            #line 247 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(single.componentTypeName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 247 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(singleMember.memberName));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n");
            
            #line 248 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
					}
            
            #line default
            #line hidden
            
            #line 249 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"

				}
				else if (singleMember_memberTypeFullName == typeof(float).FullName)
				{

            
            #line default
            #line hidden
            
            #line 254 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
					if (singleMember.isField) {
            
            #line default
            #line hidden
            this.Write("                bitStream_readFrom.ReadFloat(out _");
            
            #line 255 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(single.componentTypeName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 255 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(singleMember.memberName));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 256 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
					} else {
            
            #line default
            #line hidden
            this.Write("\t\t\t\tfloat value;\r\n                bitStream_readFrom.ReadFloat(out value);\r\n\t\t\t\t_" +
                    "");
            
            #line 259 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(single.componentTypeName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 259 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(singleMember.memberName));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n");
            
            #line 260 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
					}
            
            #line default
            #line hidden
            
            #line 261 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"

				}
				else if (singleMember_memberTypeFullName == typeof(long).FullName)
				{

            
            #line default
            #line hidden
            
            #line 266 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
					if (singleMember.isField) {
            
            #line default
            #line hidden
            this.Write("                bitStream_readFrom.ReadLong(out _");
            
            #line 267 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(single.componentTypeName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 267 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(singleMember.memberName));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 268 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
					} else {
            
            #line default
            #line hidden
            this.Write("\t\t\t\tlong value;\r\n                bitStream_readFrom.ReadLong(out value);\r\n\t\t\t\t_");
            
            #line 271 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(single.componentTypeName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 271 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(singleMember.memberName));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n");
            
            #line 272 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
					}
            
            #line default
            #line hidden
            
            #line 273 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"

				}
				else if (singleMember_memberTypeFullName == typeof(uint).FullName)
				{

            
            #line default
            #line hidden
            
            #line 278 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
					if (singleMember.isField) {
            
            #line default
            #line hidden
            this.Write("                bitStream_readFrom.ReadUInt(out _");
            
            #line 279 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(single.componentTypeName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 279 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(singleMember.memberName));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 280 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
					} else {
            
            #line default
            #line hidden
            this.Write("\t\t\t\tuint value;\r\n                bitStream_readFrom.ReadUInt(out value);\r\n\t\t\t\t_");
            
            #line 283 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(single.componentTypeName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 283 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(singleMember.memberName));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n");
            
            #line 284 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
					}
            
            #line default
            #line hidden
            
            #line 285 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"

				}
				else if (singleMember_memberTypeFullName == typeof(string).FullName)
                {

            
            #line default
            #line hidden
            
            #line 290 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
					if (singleMember.isField) {
            
            #line default
            #line hidden
            this.Write("                bitStream_readFrom.ReadString(out _");
            
            #line 291 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(single.componentTypeName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 291 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(singleMember.memberName));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 292 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
					} else {
            
            #line default
            #line hidden
            this.Write("\t\t\t\tstring value;\r\n                bitStream_readFrom.ReadString(out value);\r\n\t\t\t" +
                    "\t_");
            
            #line 295 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(single.componentTypeName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 295 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(singleMember.memberName));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n");
            
            #line 296 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
					}
            
            #line default
            #line hidden
            
            #line 297 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"

				}
				else if (singleMember_memberTypeFullName == typeof(byte).FullName)
				{

            
            #line default
            #line hidden
            this.Write("\t\t\t\t_");
            
            #line 302 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(single.componentTypeName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 302 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(singleMember.memberName));
            
            #line default
            #line hidden
            this.Write(" = (byte)bitStream_readFrom.ReadByte();\r\n");
            
            #line 303 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"

				}
				else if (singleMember_memberTypeFullName == typeof(ushort).FullName)
				{

            
            #line default
            #line hidden
            
            #line 308 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
					if (singleMember.isField) {
            
            #line default
            #line hidden
            this.Write("                bitStream_readFrom.ReadUShort(out _");
            
            #line 309 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(single.componentTypeName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 309 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(singleMember.memberName));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 310 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
					} else {
            
            #line default
            #line hidden
            this.Write("\t\t\t\tushort value;\r\n                bitStream_readFrom.ReadUShort(out value);\r\n\t\t\t" +
                    "\t_");
            
            #line 313 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(single.componentTypeName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 313 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(singleMember.memberName));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n");
            
            #line 314 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
					}
            
            #line default
            #line hidden
            
            #line 315 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"

				}
                else if (singleMember_memberTypeFullName == typeof(short).FullName)
				{

            
            #line default
            #line hidden
            this.Write("\t\t\t\tint count = 2;\r\n\t\t\t\tbyte[] bytes = new byte[count];");
            
            #line 321 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
 /* TODO: new byte array!!!! no no no, use pool here! */ 
            
            #line default
            #line hidden
            this.Write("\t\t\t\tfor (int i = 0; i < count; ++i)\r\n\t\t\t\t{\r\n\t\t\t\t\tbyte b = (byte)bitStream_readFro" +
                    "m.ReadByte();\r\n\t\t\t\t\tbytes[i] = b;\r\n\t\t\t\t}\r\n\t\t\t\t_");
            
            #line 327 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(single.componentTypeName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 327 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(singleMember.memberName));
            
            #line default
            #line hidden
            this.Write(" = BitConverter.ToInt16(bytes, 0);\r\n");
            
            #line 328 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"

				}
                else if (singleMember_memberTypeFullName == typeof(int).FullName)
				{

            
            #line default
            #line hidden
            this.Write("\t\t\t\tint count = 4;\r\n\t\t\t\tbyte[] bytes = new byte[count];");
            
            #line 334 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
 /* TODO: new byte array!!!! no no no, use pool here! */ 
            
            #line default
            #line hidden
            this.Write("\t\t\t\tfor (int i = 0; i < count; ++i)\r\n\t\t\t\t{\r\n\t\t\t\t\tbyte b = (byte)bitStream_readFro" +
                    "m.ReadByte();\r\n\t\t\t\t\tbytes[i] = b;\r\n\t\t\t\t}\r\n\t\t\t\t_");
            
            #line 340 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(single.componentTypeName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 340 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(singleMember.memberName));
            
            #line default
            #line hidden
            this.Write(" = BitConverter.ToInt32(bytes, 0);\r\n");
            
            #line 341 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"

				}
                else if (singleMember_memberTypeFullName == typeof(sbyte).FullName)
				{

            
            #line default
            #line hidden
            this.Write("\t\t\t\t_");
            
            #line 346 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(single.componentTypeName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 346 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(singleMember.memberName));
            
            #line default
            #line hidden
            this.Write(" = (sbyte)bitStream_readFrom.ReadByte();\r\n");
            
            #line 347 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"

				}
                else if (singleMember_memberTypeFullName == typeof(double).FullName)
				{

            
            #line default
            #line hidden
            this.Write("\t\t\t\tint count = 8;\r\n\t\t\t\tbyte[] bytes = new byte[count];");
            
            #line 353 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
 /* TODO: new byte array!!!! no no no, use pool here! */ 
            
            #line default
            #line hidden
            this.Write("\t\t\t\tfor (int i = 0; i < count; ++i)\r\n\t\t\t\t{\r\n\t\t\t\t\tbyte b = (byte)bitStream_readFro" +
                    "m.ReadByte();\r\n\t\t\t\t\tbytes[i] = b;\r\n\t\t\t\t}\r\n\t\t\t\t_");
            
            #line 359 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(single.componentTypeName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 359 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(singleMember.memberName));
            
            #line default
            #line hidden
            this.Write(" = BitConverter.ToDouble(bytes, 0);\r\n");
            
            #line 360 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"

				}
			}
            
            #line default
            #line hidden
            this.Write("\t\t\t}\r\n");
            
            #line 364 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
		}
	}

            
            #line default
            #line hidden
            this.Write(@"        }

        /// <summary>
        ///  Deserializes a ginel value (using <paramref name=""singleIndex""/> to know which) from <paramref name=""bitStream_readFrom""/>
        ///  and uses them to modify appropriate member variables internally.
        /// </summary>
        internal override void DeserializeInitSingle(Utils.BitStream bitStream_readFrom, byte singleIndex)
        {
            throw new NotImplementedException();
        }

		internal override void UpdateLastKnownValues()
		{
");
            
            #line 380 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"

	iOverall = 0;
	singleCount = uniqueEntry.ComponentMemberNames_By_ComponentTypeFullName.Length;
	for (int iSingle = 0; iSingle < singleCount; ++iSingle)
	{
		GONetParticipant_ComponentsWithAutoSyncMembers_Single single = uniqueEntry.ComponentMemberNames_By_ComponentTypeFullName[iSingle];
		int singleMemberCount = single.autoSyncMembers.Length;
		for (int iSingleMember = 0; iSingleMember < singleMemberCount; ++iSingleMember)
        {
			GONetParticipant_ComponentsWithAutoSyncMembers_SingleMember singleMember = single.autoSyncMembers[iSingleMember];

            
            #line default
            #line hidden
            this.Write("\t\t\t\tvaluesChangesSupport[");
            
            #line 391 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(iOverall));
            
            #line default
            #line hidden
            this.Write("].lastKnownValue_previous = valuesChangesSupport[");
            
            #line 391 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(iOverall));
            
            #line default
            #line hidden
            this.Write("].lastKnownValue;\r\n\t\t\t\tvaluesChangesSupport[");
            
            #line 392 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(iOverall));
            
            #line default
            #line hidden
            this.Write("].lastKnownValue = ");
            
            #line 392 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(single.componentTypeName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 392 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(singleMember.memberName));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n");
            
            #line 394 "C:\projects\unity\gonet\Assets\Code\GONet\Editor\Generation\GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplate.tt"
		
			iOverall++;
		}
	}

            
            #line default
            #line hidden
            this.Write("\t\t}\r\n    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public class GONetParticipant_AutoMagicalSyncCompanion_GeneratedTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
